apiVersion: v1
kind: Namespace
metadata:
  name: e2e-performance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: e2e-performance
  name: e2e-performance-serviceaccount
  namespace: e2e-performance
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    component: e2e-performance
  name: e2e-performance-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: e2e-performance-serviceaccount
subjects:
- kind: ServiceAccount
  name: e2e-performance-serviceaccount
  namespace: e2e-performance
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    component: e2e-performance
  name: e2e-performance-serviceaccount
  namespace: e2e-performance
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: v1
kind: Pod
metadata:
  name: e2e-performance
  namespace: e2e-performance
spec:
  containers:
  - name: e2e-performance
    image: wadelee/e2e-performance:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command: ["/bin/sh"]
    args: ["-c", "/run_e2e.sh && sleep 3600"]
    env:
    - name: E2E_FOCUS
      value: \[Feature:Performance\]
    volumeMounts:
    - name: output-volume
      mountPath: /tmp/results
    - name: root
      mountPath: /node
      readOnly: false
  volumes:
  - name: output-volume
    hostPath:
      path: /tmp/results
  - name: root
    hostPath:
      path: /
  restartPolicy: Never
  serviceAccountName: e2e-performance-serviceaccount
  hostIPC: true
  hostNetwork: true
  hostPID: true